#############################################################################
# JupyterBook settings
title                       : An Idiosyncratic Subset of Statistics  # The title of the book. Will be placed in the left navbar.
author                      : Philip B. Stark  # The author of the book
copyright                   : "2023"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

execute:
  execute_notebooks: 'off'

# Enable some myst extensions beyond the default.
parse:
  myst_enable_extensions: 
    - amsmath
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - colon_fence
    - substitution

# Add links to GitHub repo
# For more info: https://jupyterbook.org/en/stable/basics/repository.html
repository:
  url: https://github.com/pbstark/StatNotes
  branch: main
html:
  use_repository_button: true
  use_issues_button: true

# Uncomment this later if bibliographic references are desired
# See: https://jupyterbook.org/en/stable/tutorials/references.html

# bibtex_bibfiles:
#   - references.bib
# sphinx:
#   config:
#     bibtex_reference_style: author_year
